//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomMembershipDB : DbContext
    {
        public CustomMembershipDB()
            : base("name=CustomMembershipDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applications> Applications { get; set; }
        public DbSet<FAQ> FAQ { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<Memberships> Memberships { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<ShopItem> ShopItem { get; set; }
        public DbSet<SiteMainPages> SiteMainPages { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<GalleryImages> GalleryImages { get; set; }
        public DbSet<GalleryPages> GalleryPages { get; set; }
        public DbSet<EfarganPages> EfarganPages { get; set; }
        public DbSet<EfarganPagesParagraphs> EfarganPagesParagraphs { get; set; }
        public DbSet<EfarganPagesSliders> EfarganPagesSliders { get; set; }
        public DbSet<EfarganPagesTickers> EfarganPagesTickers { get; set; }
        public DbSet<EfarganLanguage> EfarganLanguage { get; set; }
        public DbSet<EfarganPagesBlog> EfarganPagesBlog { get; set; }
        public DbSet<EfarganPagesBlogReplies> EfarganPagesBlogReplies { get; set; }
        public DbSet<EfarganPagesLanguage> EfarganPagesLanguage { get; set; }
    }
}
