//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfarganPagesBlog
    {
        public int Id { get; set; }
        public string MetaTag { get; set; }
        public string DescriptionTag { get; set; }
        public string TitleTag { get; set; }
        public string Text { get; set; }
    }
}
