//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfarganPagesSliders
    {
        public int Id { get; set; }
        public string SliderTitle { get; set; }
        public string SliderText { get; set; }
        public string SliderLinkText { get; set; }
        public string SliderLinkURL { get; set; }
        public string SliderImageURL { get; set; }
        public string SliderImageFileName { get; set; }
        public Nullable<int> SliderEfarganPagesId { get; set; }
        public Nullable<int> SliderEfarganPagesLanguageId { get; set; }
    
        public virtual EfarganPages EfarganPages { get; set; }
        public virtual EfarganPagesLanguage EfarganPagesLanguage { get; set; }
    }
}
