//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfarganPagesLanguage
    {
        public int Id { get; set; }
        public string MetaTag { get; set; }
        public string DescriptionTag { get; set; }
        public string TitleTag { get; set; }
        public string TicketTitle { get; set; }
        public string TicketLinkText { get; set; }
        public string TicketLinkURL { get; set; }
        public Nullable<int> EfarganLanguageRef { get; set; }
        public Nullable<int> EfarganPagesIdRef { get; set; }
    
        public virtual EfarganLanguage EfarganLanguage { get; set; }
        public virtual EfarganPages EfarganPages { get; set; }
    }
}
