//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfarganPages
    {
        public EfarganPages()
        {
            this.EfarganPagesLanguage = new HashSet<EfarganPagesLanguage>();
            this.EfarganPagesParagraphs = new HashSet<EfarganPagesParagraphs>();
            this.EfarganPagesSliders = new HashSet<EfarganPagesSliders>();
            this.EfarganPagesTickers = new HashSet<EfarganPagesTickers>();
        }
    
        public int Id { get; set; }
        public string MetaTag { get; set; }
        public string DescriptionTag { get; set; }
        public string TitleTag { get; set; }
        public string TicketTitle { get; set; }
        public string TicketLinkText { get; set; }
        public string TicketLinkURL { get; set; }
        public string MenuText { get; set; }
    
        public virtual ICollection<EfarganPagesLanguage> EfarganPagesLanguage { get; set; }
        public virtual ICollection<EfarganPagesParagraphs> EfarganPagesParagraphs { get; set; }
        public virtual ICollection<EfarganPagesSliders> EfarganPagesSliders { get; set; }
        public virtual ICollection<EfarganPagesTickers> EfarganPagesTickers { get; set; }
    }
}
