//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfarganLanguage
    {
        public EfarganLanguage()
        {
            this.EfarganPagesLanguage = new HashSet<EfarganPagesLanguage>();
        }
    
        public int Id { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<EfarganPagesLanguage> EfarganPagesLanguage { get; set; }
    }
}
