//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfarganPagesTickers
    {
        public int Id { get; set; }
        public string TickerTitle { get; set; }
        public string TickerText { get; set; }
        public string TickerLinkText { get; set; }
        public string TickerLinkURL { get; set; }
        public Nullable<int> TickerEfarganPagesId { get; set; }
        public Nullable<int> TickerEfarganPagesLanguageId { get; set; }
    
        public virtual EfarganPages EfarganPages { get; set; }
        public virtual EfarganPagesLanguage EfarganPagesLanguage { get; set; }
    }
}
