//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public FAQ()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> QUserId { get; set; }
        public Nullable<int> AUserId { get; set; }
        public bool NotifyByEmail { get; set; }
        public string NotifyEmail { get; set; }
    
        public virtual ICollection<Images> Images { get; set; }
    }
}
