//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryPages
    {
        public GalleryPages()
        {
            this.GalleryImages = new HashSet<GalleryImages>();
        }
    
        public int Id { get; set; }
        public string MetaTag { get; set; }
        public string DescriptionTag { get; set; }
        public string TitleTag { get; set; }
        public string Title { get; set; }
        public string TitleImage { get; set; }
        public string Body { get; set; }
        public string BodyImage { get; set; }
        public string Footer { get; set; }
        public string FooterImage { get; set; }
    
        public virtual ICollection<GalleryImages> GalleryImages { get; set; }
    }
}
