//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTimer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItem
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemImage { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<System.DateTime> ItemAddDate { get; set; }
        public Nullable<System.DateTime> ItemExpirationDate { get; set; }
    }
}
